version: "3"
services:
  server:
    build:
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - redis
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app/serve
    env_file: .env

  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
